### ISSUE TITLE
Update to work in StarUML v5.0.2?

### ISSUE THREAD

**Issue by CobaltMongoose** [staruml/staruml-csharp#20]
The current version of StarUML will not allow this extension to install. The install button is greyed out with warning "This extension currently only works with older versions of StarUML"

![CannotImport](https://user-images.githubusercontent.com/34733276/196030937-f856f671-f98f-4f2b-b545-ffb677c79432.PNG)

I tried downloading a local copy of the extension and pointing StarUML's Extension Manager to the local folder but install failed with:
"Unknown Internal Error"
so, I probably did that wrong. I tried with the contents in a zip folder and an extracted folder.

![Failure](https://user-images.githubusercontent.com/34733276/196031237-0ccecfc4-8d1b-4204-83dc-0f7668432e0f.PNG)

Is there a way to update this extension to work with StarUML v5.0.2?

**Comment by niklauslee** [comment]
Fixed in registry database. Now available in v5.x. Thanks.
